#!/bin/bash

pgm=$(echo $0|sed -e 's/-.*//')
os=$(uname -s)
hw=$(uname -m)

case "$os-$hw" in
  Darwin-arm64)
    $pgm-mach-arm64 $@
    ;;
  Darwin-x86_64)
    $pgm-mach-x86_64 $@
    ;;
  Darwin-i?86)
    $pgm-mach-i386 $@
    ;;
  Darwin-Power*)
    $pgm-mach-ppc $@
    ;;
  Linux-i?86)
    $pgm-elf-linux $@
    ;;
  Sun*-sparc*)
    $pgm-elf-sparc $@
    ;;
  *)
    echo "Unknown OS - unable to determine executable";
    break;;
esac
